version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3500:80'
    env_file:
      - ./.env
    environment:
      - 'NODE_ENV=development'
